name: "Hello World"
version: "1.0.0"
slug: "hello_world"
description: "My first Home Assistant add-on"
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
init: false

# Use a public base image
image: "ghcr.io/home-assistant/amd64-base:latest"

# Command to run
command: >
  bash -c "echo 'Hello World!' && sleep infinity"

