---

name: "Invoice App"
version: "1.0.0"
slug: "invoice_app"
description: "FastAPI-based Invoice Management App"
arch:
  - amd64
startup: services
boot: auto
init: false

# Pull private Docker Hub image
image: "tsrattan/invoice-app:latest"

environment:
  DATABASE_URL: "sqlite:////app/uploads/invoices_new.db"
  UPLOAD_DIR: "/app/uploads"
  TZ: "Australia/Sydney"

# Mount HA host folder for uploads
volumes:
  - /share/invoice_uploads:/app/uploadsi:rw

# Enable Ingress for running inside Home Assistant sidebar
ingress: true
panel_icon: mdi:file-document
panel_title: "Invoice App"

ports:
  8000/tcp: 8000
