name: "Invoice App"
version: "1.0.0"
slug: "invoice_app"
description: "FastAPI-based Invoice Management App"
arch:
  - amd64
startup: services
boot: auto
init: false

# Use a Dockerfile inside the add-on folder instead of private image
build:
  context: .
  dockerfile: Dockerfile

environment:
  DATABASE_URL: "sqlite:////app/uploads/invoices_new.db"
  UPLOAD_DIR: "/app/uploads"
  TZ: "Australia/Sydney"

volumes:
  - /share/invoice_uploads:/app/uploads:rw

ingress: true
panel_icon: mdi:file-document
panel_title: "Invoice App"

